= Quick guide for Asciidoctor using maven
:toc:
:source-highligher: coderay


:numbered:
== Asciidoctor is a tool chain
* Asciidoctor support a chain of action to create a document +
* A simple scenario is that (asciidoc) -> (docbook) -> (pdf) +
* To fulfill what needed, we could combine these tools together. +
* *Maven* - a project management tool, we could use to create that chain. +



== Getting familiar with syntax +

=== Basic syntax
* `* somthing *` mean : **This is a bold text** +
* This is copy right symbol: (C) +
* A right arrow: `- >` : -> +
* #Silver# can *kill* #Werewolves#

=== Listing
include::listing[]

=== Table

=== Source code
[source, javascript]
----
var fn = function(){
  console.log('hello!!!!')
}
----

:markup-in-source: verbatim,quotes

[source,java,subs="{markup-in-source}"]
----
System.out.println("Hello *bold* text").
----


=== Marco

== Using asciidoctor with maven

=== To HTML5
* Install maven from http://maven.apache.org/download.cgi[maven]
* Create a simple project
[source, bash]
----
mvn archetype:generate -DgroupId=group -DartifactId=pjname -DinteractiveMode=false
----
* Add dependency to pom file
[source, xml]
----
<groupId>org.asciidoctor</groupId>
<artifactId>asciidoctor-maven-plugin</artifactId>
<version>1.5.2</version>
----
NOTE: By using this lib, we could config our project to generate html5 type without any other dependencies.

* A finished config pom file could look like this
[source, xml]
----
<build>
  <defaultGoal>process-resources</defaultGoal>
  <plugins>
    <plugin>
      <groupId>org.asciidoctor</groupId>
      <artifactId>asciidoctor-maven-plugin</artifactId>
      <version>1.5.2</version>
      <configuration>
        <sourceDirectory>src/document</sourceDirectory>
        <attributes>
          <sourceDir>${project.build.sourceDirectory}</sourceDir>
        </attributes>
      </configuration>
      <executions>
        <execution>
          <id>gen html </id>
          <phase>generate-resources</phase>
          <goals>
            <goal>process-asciidoc</goal>
          </goals>
          <configuration>
            <backend>html5</backend>
            <doctype>book</doctype>
          </configuration>
        </execution>
      </executions>
    </plugin>
  </plugins>
</build
----

* Build project
[source, bash]
....
mvn clean compile
....

=== To PDF
* We just need to add more dependencies to pom file

[source, xml]
....
<dependency>
  <groupId>org.asciidoctor</groupId>
  <artifactId>asciidoctorj-pdf</artifactId>
  <version>1.5.0-alpha.6</version>
</dependency>
....

* And more config

[source, xml]
....
<configuration>
  <backend>pdf</backend>
  <sourceHighlighter>coderay</sourceHighlighter>
  <attributes>
    <toc/>
    <pagenums/>
  </attributes>
</configuration>
....

* Build project
[source, bash]
....
mvn clean compile
....

* Complete [pom] file

